name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.15
  go_router: ^14.6.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  table_calendar: ^3.1.2
  dio: ^5.7.0
  socket_io_client: ^3.0.2
  collection: ^1.18.0
  event_bus: ^2.0.1
  intl: ^0.19.0
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  

flutter:
  uses-material-design: true
  assets:
    - assets/images/default_event_thumb.png
    - assets/images/default_community.png
    - assets/images/default_event.png
    - assets/images/default_user.png
    - assets/images/logo.svg
    